version: '3'
services:
  web:
    build: .
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./:/home/app/
    depends_on:
      - database
    # restart_policy:
    #     condition: on-failure
    # restart: always
  database:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
